# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61a0ff43be6b7d95031e522ebaa761f7ef6553b29a645ee1c1122a2dd56e9d6961d72c9c5be5fb13144688ff486382569484fc8d7da5516fc715b17e5f8a7eca

test:
  secret_key_base: 86856b9666e597f7be3296dd438f3c20d24787a0fa135d41bbc810d1437f389f1cc18c6bd0f2b0e0e944e0dc2bfec20bc7ed4397a6da0ef82bf7edec95483c52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
